;;; swagger-to-org-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from swagger-to-org.el

(autoload 'swagger-to-org-from-file-name "swagger-to-org" "\
Generate the org output from an input swagger file, given FN for the file name.

(fn FN)" t)
(register-definition-prefixes "swagger-to-org" '("swagger-to-org-"))

;;; End of scraped data

(provide 'swagger-to-org-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; swagger-to-org-autoloads.el ends here
